### ISSUE TITLE
Verify all internal docs for each function in Background, Perturbations, Tracers, PowerSpectra, AngularTwoPoint

### ISSUE THREAD

**Issue by gcanasherrera** [cloe-org/cloelib#23]
## ✅ Task: Verify Internal Documentation for `cloelib`

**Description:**  
Review and verify the internal docstrings and inline comments for all public and private functions within the `cloelib` module. Ensure that all documentation is clear, consistent with our coding standards, and provides sufficient context for developers and users.

### Checklist
- [ ] Each function has a complete docstring (description, arguments, return type, exceptions if any).
- [ ] Consistent formatting is used (e.g., NumPy or Google style).
- [ ] Parameter names in the docstring match the function signature.
- [ ] Descriptions are clear, concise, and unambiguous.
- [ ] Missing or outdated documentation is added or updated.
- [ ] Inline comments are meaningful and helpful (not redundant with code).
- [ ] Any misleading or incorrect documentation is fixed or flagged.

### Additional Notes
- Prioritize user-facing or frequently modified functions.
- Open separate issues or PRs for any larger refactors identified.

**Target files:**  
`cloelib/*.py`

**Comment by gcanasherrera** [comment]
@marcobonici should we get help wanted?

**Comment by marcobonici** [comment]
Yes.
Should we chat with Amandine/Sam...?

**Comment by gcanasherrera** [comment]
Priority medium, also dependency on the current open PR. After Leiden?

**Comment by marcobonici** [comment]
The only thing is that at this moment Amandine is not working on anything Cloe related and she is asking to help.
If she is available, I would consider asking her to help now (although I agree, priority is medium.).

**Comment by gcanasherrera** [comment]
Do we have the time to have somebody new on board and guide it through the new structure of repos before Leiden? If so, I would advocate to include first a contribution guideline and use this opportunity to test if the guideline is good by getting Amandine on board.

**Comment by gcanasherrera** [comment]
For the pending API @stefanodavini you can recycle this task

**Comment by stefanodavini** [comment]
As a result of issue #168, placeholders for docstrings were added in `jax_cosmology.py `and `math_utils.py`.
The docstring to look for is `"""Write documentation (TODO)."""`

**Comment by gcanasherrera** [comment]
@amandinelebrun this is the task we need help with: check the internal docs of these functions. Would be happy to give us a hand with this?

**Comment by santiagocasas** [comment]
Here a very good guide about writing documentation:  https://www.writethedocs.org/guide/

**Comment by gcanasherrera** [comment]
@amandinelebrun this is the task. We already have the docs deployed thanks to @marcobonici .

**Comment by gcanasherrera** [comment]
@amandinelebrun , do you think that after the euroHPC deadline, we could have a look at this...?

**Comment by amandinelebrun** [comment]
Absolutely @gcanasherrera. Remind me after Nov. 5 when the HPCI (Japan) one is out of the door as well if you do not hear from me.

**Comment by gcanasherrera** [comment]
Sorry @amandinelebrun , but do you think you will find eventually some time to work on this? If not, we can find another volunteer.

**Comment by amandinelebrun** [comment]
Apologies for the silence. I am moving it to the top of my list for the next few weeks.

**Comment by amandinelebrun** [comment]
@gcanasherrera The link to the documentation style guide in this issue description circularly sends back to this issue. I have looked and could not find the corresponding page in either the organisation or the repository. Sorry about this stupid query.

**Comment by gcanasherrera** [comment]
You don't need a link for this, though, it should be done at the level of the docs in the code. In any case: https://cloe-org.github.io/cloelib/dev/api/

**Comment by amandinelebrun** [comment]
> You don't need a link for this, though, it should be done at the level of the docs in the code. In any case: https://cloe-org.github.io/cloelib/dev/api/

I had found this. Sorry for being unclear, I meant that I could not find the documentation style guide, which is mentioned in the additional notes of the issue description.

**Comment by gcanasherrera** [comment]
Typo
